substitutions:
  friendly_name: Zehnder ComfoAir Q
  device_name: zehnder-comfoair-q
  device_description: Zehnder ComfoAir Q HRV (heat recovery ventilation) unit
  filter_time: 5s
  filter_send_every: "1"
  filter_window_size: "3"

packages:
  binary_sensors: !include binary_sensors.yml
  board: !include board.yml
  button: !include button.yml
  canbus: !include canbus.yml
  climate: !include climate.yml
  common: !include common.yml
  comfoair: !include zehnder_comfoair_q.yml
  fan: !include fan.yml
  project: !include project.yml
  select: !include select.yml
  sensors: !include sensors.yml
  switch: !include switch.yml
  text_sensors: !include text_sensors.yml

esphome:
  name: ${device_name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  comment: ${device_description}

logger:
  level: INFO
  logs:
    canbus: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  enable_rrm: true
  enable_btm: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_hotspot_password

captive_portal:
improv_serial:

web_server:
  port: 80
  ota: false
  local: true
